# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d61e5f72e0b39a44ee27df93334d2815eddc13918cd5b51ebf82c13a78c9926a366c6f8abfcf72aa77943910328d5baaac5be30aec4b3fe93333832021931293

test:
  secret_key_base: d361ae386f0a59170409b446596d7e6632f0a9f194720d228fb2e079d7ac4f65d9080a125deb182cce63f9abc32fe2cacd412a3fe121517b5683fcb3dd80f59f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
